apiVersion: v1
kind: Service
metadata:
  name: presto
spec:
  type: NodePort
  ports:
    - name: client
      port: 8080
      nodePort: 32766
  selector:
    app: presto
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: presto
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: presto
    spec:
      containers:
        - name: presto
          image: shawnzhu/prestodb:0.215
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: home/presto/etc
              name: presto-etc
      volumes:
        - name: presto-etc
          hostPath:
            path: "/presto-etc"
